// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification emitted when the available skills catalog changes.
 *
 * Treat this as an invalidation signal and re-run `skills/list` with the
 * client's current parameters when refreshed skill metadata is needed.
 */
export type SkillsChangedNotification = {
/**
 * The affected thread, or `None` for a process-wide local skill change.
 */
threadId: string | null, };
