// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillsListEntry } from "./SkillsListEntry";
import type { ThreadSkillMetadata } from "./ThreadSkillMetadata";

export type SkillsListResponse = { data: Array<SkillsListEntry>,
/**
 * Skills contributed by selected capability roots for the requested thread.
 */
threadSkills: Array<ThreadSkillMetadata>, };
