// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadSkillMetadata = { name: string, description: string, shortDescription: string | null,
/**
 * Stable executor-owned locator used for display and deduplication.
 */
resource: string, enabled: boolean, };
